; Script generated by simple-inno-setup-script.
[Setup]
AppId=6276740f-6aae-4337-9e85-e6bfbdb1d9e8
SignTool=signtool
AppName=carlo-plate
AppVersion=0.0.1
AppVerName=carlo-plate 0.0.1
AppPublisher=simple-inno
AppPublisherURL=
AppSupportURL=
AppUpdatesURL=
DefaultDirName={pf}\carlo-plate
DefaultGroupName=carlo-plate
AllowNoIcons=yes
OutputDir=../carlo-plate
OutputBaseFilename=carlo-plate-setup
SolidCompression=yes
PrivilegesRequired=none
InternalCompressLevel=ultra64
ShowTasksTreeLines=false
DisableReadyPage=True
DisableReadyMemo=True
DisableFinishedPage=True
UsePreviousSetupType=False
UsePreviousTasks=False
UsePreviousLanguage=False
FlatComponentsList=False
AlwaysShowComponentsList=False
ShowComponentSizes=False
ArchitecturesInstallIn64BitMode=x64

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; x64
Source: "build/executables/carlo-plate-win-x64.exe"; DestDir: "{pf}/carlo-plate"; DestName: "carlo-plate.exe"; Check: Is64BitInstallMode
; x86
Source: "build/executables/carlo-plate-win-x86.exe"; DestDir: "{pf}/carlo-plate"; DestName: "carlo-plate.exe"; Check: not Is64BitInstallMode; Flags: solidbreak
; common files
Source: "C:\Workspace\simple-inno-setup-script\lib\vbs.vbs"; DestDir: "{cf}/carlo-plate/carlo-plate.vbs"; Flags: solidbreak
; include aditional files (or something else...)


[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkablealone
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Icons]
()=>icons

[Run]
Filename: "{userdesktop}/carlo-plate.lnk"; Flags: nowait skipifsilent runascurrentuser shellexec; Description: "{cm:LaunchProgram,{#StringChange('carlo-plate', '&', '&&')}}"
